### PR TITLE
New fancy logo

### PR DESCRIPTION
**Pull request by saiyam1814**

### CODE REVIEW

**Comment by 0xE282B0** [comment]
Thanks, that's super cool!

Two small requests:
- [ ] can you upload a vector version, e.g. as SVG?
- [ ] can we make the background transparent?

**Comment by saiyam1814** [comment]
> Thanks, that's super cool!
> 
> Two small requests:
> 
> * [ ]  can you upload a vector version, e.g. as SVG?
> * [ ]  can we make the background transparent?

earlier it was logo.png right? at which location should I put the vector version? Transparent can be done easily.

**Comment by 0xE282B0** [comment]
Yes, it was PNG before but that should not be the long-term solution. 
The `docs/assets` folder is fine. 😊

**Comment by saiyam1814** [comment]
Hey the changes are done, have a look.

**Comment by 0xE282B0** [comment]
Awesome!

**Pull request merged**
